package com.smartinterview.config;

import com.smartinterview.entity.DSAProblem;
import com.smartinterview.entity.InterviewQuestion;
import com.smartinterview.entity.Question;
import com.smartinterview.repository.DSAProblemRepository;
import com.smartinterview.repository.InterviewQuestionRepository;
import com.smartinterview.repository.QuestionRepository;
import lombok.RequiredArgsConstructor;
import org.springframework.boot.CommandLineRunner;
import org.springframework.stereotype.Component;

import java.util.Arrays;

@Component
@RequiredArgsConstructor
public class DataLoader implements CommandLineRunner {

    private final QuestionRepository questionRepository;
    private final InterviewQuestionRepository interviewQuestionRepository;
    private final DSAProblemRepository dsaProblemRepository;

    @Override
    public void run(String... args) throws Exception {
        questionRepository.deleteAll();
        dsaProblemRepository.deleteAll();
        interviewQuestionRepository.deleteAll();

        seedAptitudeQuestions();
        seedDSAProblems();
        seedInterviewQuestions();
    }

    private void seedAptitudeQuestions() {
        questionRepository.saveAll(Arrays.asList(
            Question.builder().title("A train running at the speed of 60 km/hr crosses a pole in 9 seconds. What is the length of the train?").optionA("120 metres").optionB("180 metres").optionC("324 metres").optionD("150 metres").correctAnswer("D").category("Quantitative Aptitude").difficulty("Medium").explanation("Speed = 60*(5/18) m/sec = 50/3 m/sec. Length = Speed * Time = (50/3) * 9 = 150 metres.").build(),
            Question.builder().title("Find the greatest number that will divide 43, 91 and 183 so as to leave the same remainder in each case.").optionA("4").optionB("7").optionC("9").optionD("13").correctAnswer("A").category("Quantitative Aptitude").difficulty("Hard").explanation("Required number = H.C.F. of (91-43), (183-91) and (183-43) = H.C.F. of 48, 92 and 140 = 4.").build(),
            Question.builder().title("The price of a commodity is increased by 25%. By what percentage must a consumer reduce their consumption so that the expenditure remains the same?").optionA("20%").optionB("25%").optionC("16.66%").optionD("33.33%").correctAnswer("A").category("Quantitative Aptitude").difficulty("Medium").explanation("Reduction % = (R / (100 + R)) * 100 = (25/125)*100 = 20%.").build(),
            Question.builder().title("If A is the brother of B; B is the sister of C; and C is the father of D, how D is related to A?").optionA("Brother").optionB("Sister").optionC("Nephew or Niece").optionD("Cannot be determined").correctAnswer("D").category("Logical Reasoning").difficulty("Medium").explanation("Gender of D is not given. Therefore, D can be either Nephew or Niece.").build(),
            Question.builder().title("Choose the word which is the exact OPPOSITE of the given words: ENORMOUS").optionA("Soft").optionB("Average").optionC("Tiny").optionD("Weak").correctAnswer("C").category("Verbal Ability").difficulty("Easy").explanation("Enormous means very large, so the opposite is Tiny.").build(),
            Question.builder().title("What is the next number in the series: 2, 5, 10, 17, 26, ...").optionA("35").optionB("37").optionC("39").optionD("41").correctAnswer("B").category("Logical Reasoning").difficulty("Easy").explanation("The differences are 3, 5, 7, 9. The next difference is 11. 26+11 = 37.").build(),
            Question.builder().title("Which of the following is not a prime number?").optionA("31").optionB("61").optionC("71").optionD("91").correctAnswer("D").category("Quantitative Aptitude").difficulty("Easy").explanation("91 is divisible by 7 and 13. (13 * 7 = 91).").build(),
            Question.builder().title("The ratio of ages of two students is 3:2. One is older to the other by 5 years. What is the age of the younger student?").optionA("10 years").optionB("15 years").optionC("20 years").optionD("25 years").correctAnswer("A").category("Quantitative Aptitude").difficulty("Easy").explanation("Let ages be 3x and 2x. 3x - 2x = 5 => x = 5. Younger age = 2x = 10 years.").build(),
            Question.builder().title("If PAINT is coded as 74128 and EXCEL is coded as 93596, then how would you encode ACCEPT?").optionA("455978").optionB("547978").optionC("554978").optionD("455968").correctAnswer("A").category("Logical Reasoning").difficulty("Medium").explanation("A=4, C=5, C=5, E=9, P=7, T=8. So ACCEPT is 455978.").build(),
            Question.builder().title("Identify the correctly spelt word.").optionA("Accommodate").optionB("Accomodate").optionC("Acomodate").optionD("Acommodate").correctAnswer("A").category("Verbal Ability").difficulty("Medium").explanation("'Accommodate' has double 'c' and double 'm'.").build(),
            Question.builder().title("A can do a work in 15 days and B in 20 days. If they work on it together for 4 days, then the fraction of the work that is left is:").optionA("1/4").optionB("1/10").optionC("7/15").optionD("8/15").correctAnswer("D").category("Quantitative Aptitude").difficulty("Hard").explanation("A's 1 day work = 1/15, B's 1 day work = 1/20. Together in 4 days = 4*(1/15 + 1/20) = 4*(7/60) = 7/15. Work left = 1 - 7/15 = 8/15.").build(),
            Question.builder().title("Find the odd one out: 3, 5, 11, 14, 17, 21").optionA("21").optionB("17").optionC("14").optionD("3").correctAnswer("C").category("Logical Reasoning").difficulty("Medium").explanation("All numbers except 14 are odd numbers. (Alternatively, all others except 14 and 21 are primes, but 14 is the only even number).").build(),
            Question.builder().title("If the cost price is 25% of selling price, then what is the profit percentage?").optionA("150%").optionB("200%").optionC("300%").optionD("350%").correctAnswer("C").category("Quantitative Aptitude").difficulty("Medium").explanation("Let SP = 100, then CP = 25. Profit = 75. Profit % = (75/25)*100 = 300%.").build(),
            Question.builder().title("P is the brother of Q and R. S is R's mother. T is P's father. Which of the following statements cannot be definitely true?").optionA("T is Q's father").optionB("S is P's mother").optionC("P is S's son").optionD("Q is T's son").correctAnswer("D").category("Logical Reasoning").difficulty("Hard").explanation("Gender of Q is not known. Q could be T's daughter.").build(),
            Question.builder().title("Choose the correct synonym for 'MITIGATE'.").optionA("Aggravate").optionB("Relieve").optionC("Extend").optionD("Abolish").correctAnswer("B").category("Verbal Ability").difficulty("Easy").explanation("Mitigate means to make less severe or painful, so Relieve is the synonym.").build(),
            Question.builder().title("In a certain code, MONKEY is written as XDJMNL. How is TIGER written in that code?").optionA("QDFHS").optionB("SDFHS").optionC("SHFDQ").optionD("UJHFS").correctAnswer("A").category("Logical Reasoning").difficulty("Hard").explanation("Reverse the word: YEKNOM. Then subtract 1 from each letter: XDJMNL. TIGER -> REGIT -> QDFHS.").build(),
            Question.builder().title("Two numbers are respectively 20% and 50% more than a third number. The ratio of the two numbers is:").optionA("2:5").optionB("3:5").optionC("4:5").optionD("6:7").correctAnswer("C").category("Quantitative Aptitude").difficulty("Easy").explanation("Let third number be 100. Then first and second are 120 and 150. Ratio = 120/150 = 4:5.").build(),
            Question.builder().title("Statement: Should taxes on color televisions be further increased? \nArg 1: Yes, Color TV is a luxury item and rich people can afford it.\nArg 2: No, Televisions are bought by the poor too.").optionA("Only Arg 1 is strong").optionB("Only Arg 2 is strong").optionC("Either 1 or 2 is strong").optionD("Neither 1 nor 2 is strong").correctAnswer("A").category("Logical Reasoning").difficulty("Medium").explanation("Color TVs are generally considered luxury items compared to standard necessities, making Arg 1 stronger in an economic context.").build(),
            Question.builder().title("Complete the sentence: He ______ in the company for 10 years when he was promoted.").optionA("has been working").optionB("had been working").optionC("is working").optionD("was working").correctAnswer("B").category("Verbal Ability").difficulty("Medium").explanation("Past perfect continuous is used to show an action that was ongoing up to a point in the past.").build(),
            Question.builder().title("A sum of money at simple interest amounts to Rs. 815 in 3 years and to Rs. 854 in 4 years. The sum is:").optionA("Rs. 650").optionB("Rs. 690").optionC("Rs. 698").optionD("Rs. 700").correctAnswer("C").category("Quantitative Aptitude").difficulty("Hard").explanation("S.I. for 1 year = 854 - 815 = 39. S.I. for 3 years = 39*3 = 117. Principal = 815 - 117 = Rs. 698.").build()
        ));
    }

    private void seedDSAProblems() {
        dsaProblemRepository.saveAll(Arrays.asList(
            DSAProblem.builder().title("Two Sum").difficulty("Easy").topic("Arrays").description("Given an array of integers nums and an integer target, return indices of the two numbers such that they add up to target.\n\nYou may assume that each input would have exactly one solution, and you may not use the same element twice.").examples("Input: nums = [2,7,11,15], target = 9\nOutput: [0,1]").constraints("2 <= nums.length <= 10^4\n-10^9 <= nums[i] <= 10^9").tags("array, hash-table").youtubeLink("https://www.youtube.com/watch?v=KLlXCFG5TnA").leetcodeLink("https://leetcode.com/problems/two-sum/").solved(false).build(),
            DSAProblem.builder().title("Reverse Linked List").difficulty("Easy").topic("Linked Lists").description("Given the head of a singly linked list, reverse the list, and return the reversed list.").examples("Input: head = [1,2,3,4,5]\nOutput: [5,4,3,2,1]").constraints("The number of nodes in the list is the range [0, 5000].\n-5000 <= Node.val <= 5000").tags("linked-list, recursion").youtubeLink("https://www.youtube.com/watch?v=G0_I-ZF0S38").leetcodeLink("https://leetcode.com/problems/reverse-linked-list/").solved(false).build(),
            DSAProblem.builder().title("Longest Substring Without Repeating Characters").difficulty("Medium").topic("Strings").description("Given a string s, find the length of the longest substring without repeating characters.").examples("Input: s = \"abcabcbb\"\nOutput: 3 (The answer is \"abc\")").constraints("0 <= s.length <= 5 * 10^4\ns consists of English letters, digits, symbols and spaces.").tags("string, sliding-window, hash-table").youtubeLink("https://www.youtube.com/watch?v=wiGpQwKPb1g").leetcodeLink("https://leetcode.com/problems/longest-substring-without-repeating-characters/").solved(false).build(),
            DSAProblem.builder().title("Merge Intervals").difficulty("Medium").topic("Arrays").description("Given an array of intervals where intervals[i] = [starti, endi], merge all overlapping intervals, and return an array of the non-overlapping intervals that cover all the intervals in the input.").examples("Input: intervals = [[1,3],[2,6],[8,10],[15,18]]\nOutput: [[1,6],[8,10],[15,18]]").constraints("1 <= intervals.length <= 10^4\nintervals[i].length == 2").tags("array, sorting").youtubeLink("https://www.youtube.com/watch?v=44H3cEC2fFM").leetcodeLink("https://leetcode.com/problems/merge-intervals/").solved(false).build(),
            DSAProblem.builder().title("Valid Parentheses").difficulty("Easy").topic("Stack").description("Given a string s containing just the characters '(', ')', '{', '}', '[' and ']', determine if the input string is valid.").examples("Input: s = \"()[]{}\"\nOutput: true\n\nInput: s = \"(]\"\nOutput: false").constraints("1 <= s.length <= 10^4\ns consists of parentheses only '()[]{}'.").tags("string, stack").youtubeLink("https://www.youtube.com/watch?v=WTzjTskDFMg").leetcodeLink("https://leetcode.com/problems/valid-parentheses/").solved(false).build(),
            DSAProblem.builder().title("Binary Tree Level Order Traversal").difficulty("Medium").topic("Trees").description("Given the head of a binary tree, return the level order traversal of its nodes' values. (i.e., from left to right, level by level).").examples("Input: root = [3,9,20,null,null,15,7]\nOutput: [[3],[9,20],[15,7]]").constraints("The number of nodes in the tree is in the range [0, 2000].").tags("tree, breadth-first-search").youtubeLink("https://www.youtube.com/watch?v=6ZnyEA4gO5I").leetcodeLink("https://leetcode.com/problems/binary-tree-level-order-traversal/").solved(false).build(),
            DSAProblem.builder().title("Climbing Stairs").difficulty("Easy").topic("Dynamic Programming").description("You are climbing a staircase. It takes n steps to reach the top. Each time you can either climb 1 or 2 steps. In how many distinct ways can you climb to the top?").examples("Input: n = 3\nOutput: 3\nExplanation: 1. 1 step + 1 step + 1 step\n2. 1 step + 2 steps\n3. 2 steps + 1 step").constraints("1 <= n <= 45").tags("dynamic-programming, math, memoization").youtubeLink("https://www.youtube.com/watch?v=Y0lT9Fck7qI").leetcodeLink("https://leetcode.com/problems/climbing-stairs/").solved(false).build(),
            DSAProblem.builder().title("Number of Islands").difficulty("Medium").topic("Graphs").description("Given an m x n 2D binary grid grid which represents a map of '1's (land) and '0's (water), return the number of islands.").examples("Input: grid = [\n  [\"1\",\"1\",\"0\",\"0\",\"0\"],\n  [\"1\",\"1\",\"0\",\"0\",\"0\"],\n  [\"0\",\"0\",\"1\",\"0\",\"0\"],\n  [\"0\",\"0\",\"0\",\"1\",\"1\"]\n]\nOutput: 3").constraints("m == grid.length\nn == grid[i].length").tags("array, depth-first-search, breadth-first-search").youtubeLink("https://www.youtube.com/watch?v=pV2kpPD66nE").leetcodeLink("https://leetcode.com/problems/number-of-islands/").solved(false).build(),
            DSAProblem.builder().title("Maximum Subarray").difficulty("Medium").topic("Arrays").description("Given an integer array nums, find the subarray with the largest sum, and return its sum.").examples("Input: nums = [-2,1,-3,4,-1,2,1,-5,4]\nOutput: 6 (Subarray is [4,-1,2,1])").constraints("1 <= nums.length <= 10^5\n-10^4 <= nums[i] <= 10^4").tags("array, divide-and-conquer, dynamic-programming").youtubeLink("https://www.youtube.com/watch?v=5WZl3MMT0Eg").leetcodeLink("https://leetcode.com/problems/maximum-subarray/").solved(false).build(),
            DSAProblem.builder().title("LRU Cache").difficulty("Medium").topic("Design").description("Design a data structure that follows the constraints of a Least Recently Used (LRU) cache.").examples("Input: [\"LRUCache\", \"put\", \"put\", \"get\"]\n[[2], [1, 1], [2, 2], [1]]\nOutput: [null, null, null, 1]").constraints("1 <= capacity <= 3000\n0 <= key <= 10^4\n0 <= value <= 10^5").tags("hash-table, linked-list, design").youtubeLink("https://www.youtube.com/watch?v=7ABFKPK2hD4").leetcodeLink("https://leetcode.com/problems/lru-cache/").solved(false).build(),
            DSAProblem.builder().title("Course Schedule").difficulty("Medium").topic("Graphs").description("There are a total of numCourses courses you have to take, labeled from 0 to numCourses - 1. You are given an array prerequisites where prerequisites[i] = [ai, bi] indicates that you must take course bi first if you want to take course ai.").examples("Input: numCourses = 2, prerequisites = [[1,0]]\nOutput: true").constraints("1 <= numCourses <= 2000").tags("depth-first-search, breadth-first-search, graph, topological-sort").youtubeLink("https://www.youtube.com/watch?v=EgI5nU9etnU").leetcodeLink("https://leetcode.com/problems/course-schedule/").solved(false).build(),
            DSAProblem.builder().title("Merge k Sorted Lists").difficulty("Hard").topic("Linked Lists").description("You are given an array of k linked-lists lists, each linked-list is sorted in ascending order. Merge all the linked-lists into one sorted linked-list and return it.").examples("Input: lists = [[1,4,5],[1,3,4],[2,6]]\nOutput: [1,1,2,3,4,4,5,6]").constraints("k == lists.length\n0 <= k <= 10^4\n0 <= lists[i].length <= 500").tags("linked-list, divide-and-conquer, heap").youtubeLink("https://www.youtube.com/watch?v=q5a5OiGbT6Q").leetcodeLink("https://leetcode.com/problems/merge-k-sorted-lists/").solved(false).build(),
            DSAProblem.builder().title("Word Break").difficulty("Medium").topic("Dynamic Programming").description("Given a string s and a dictionary of strings wordDict, return true if s can be segmented into a space-separated sequence of one or more dictionary words.").examples("Input: s = \"leetcode\", wordDict = [\"leet\",\"code\"]\nOutput: true").constraints("1 <= s.length <= 300\n1 <= wordDict.length <= 1000").tags("hash-table, string, dynamic-programming").youtubeLink("https://www.youtube.com/watch?v=Sx9NNgInc3A").leetcodeLink("https://leetcode.com/problems/word-break/").solved(false).build(),
            DSAProblem.builder().title("Find Minimum in Rotated Sorted Array").difficulty("Medium").topic("Binary Search").description("Suppose an array of length n sorted in ascending order is rotated between 1 and n times. For example, the array nums = [0,1,2,4,5,6,7] might become [4,5,6,7,0,1,2]. Given the sorted rotated array nums of unique elements, return the minimum element of this array.").examples("Input: nums = [3,4,5,1,2]\nOutput: 1").constraints("n == nums.length\n1 <= n <= 5000\n-5000 <= nums[i] <= 5000").tags("array, binary-search").youtubeLink("https://www.youtube.com/watch?v=nIVW4P8b1VA").leetcodeLink("https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/").solved(false).build(),
            DSAProblem.builder().title("Product of Array Except Self").difficulty("Medium").topic("Arrays").description("Given an integer array nums, return an array answer such that answer[i] is equal to the product of all the elements of nums except nums[i].").examples("Input: nums = [1,2,3,4]\nOutput: [24,12,8,6]").constraints("2 <= nums.length <= 10^5\n-30 <= nums[i] <= 30").tags("array, prefix-sum").youtubeLink("https://www.youtube.com/watch?v=bNvIQI2wA3k").leetcodeLink("https://leetcode.com/problems/product-of-array-except-self/").solved(false).build(),
            DSAProblem.builder().title("Lowest Common Ancestor of a Binary Search Tree").difficulty("Medium").topic("Trees").description("Given a binary search tree (BST), find the lowest common ancestor (LCA) node of two given nodes in the BST.").examples("Input: root = [6,2,8,0,4,7,9,null,null,3,5], p = 2, q = 8\nOutput: 6").constraints("The number of nodes in the tree is in the range [2, 10^5].\n-10^9 <= Node.val <= 10^9").tags("tree, depth-first-search, binary-search-tree").youtubeLink("https://www.youtube.com/watch?v=gs2LMfuNN9I").leetcodeLink("https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-search-tree/").solved(false).build(),
            DSAProblem.builder().title("3Sum").difficulty("Medium").topic("Arrays").description("Given an integer array nums, return all the triplets [nums[i], nums[j], nums[k]] such that i != j, i != k, and j != k, and nums[i] + nums[j] + nums[k] == 0.").examples("Input: nums = [-1,0,1,2,-1,-4]\nOutput: [[-1,-1,2],[-1,0,1]]").constraints("3 <= nums.length <= 3000\n-10^5 <= nums[i] <= 10^5").tags("array, two-pointers, sorting").youtubeLink("https://www.youtube.com/watch?v=jzZsG8n2R9A").leetcodeLink("https://leetcode.com/problems/3sum/").solved(false).build(),
            DSAProblem.builder().title("Kth Largest Element in an Array").difficulty("Medium").topic("Heaps").description("Given an integer array nums and an integer k, return the kth largest element in the array. Note that it is the kth largest element in the sorted order, not the kth distinct element.").examples("Input: nums = [3,2,1,5,6,4], k = 2\nOutput: 5").constraints("1 <= k <= nums.length <= 10^5\n-10^4 <= nums[i] <= 10^4").tags("array, divide-and-conquer, sorting, heap").youtubeLink("https://www.youtube.com/watch?v=XEmy13g1Qxc").leetcodeLink("https://leetcode.com/problems/kth-largest-element-in-an-array/").solved(false).build(),
            DSAProblem.builder().title("Search in Rotated Sorted Array").difficulty("Medium").topic("Binary Search").description("Given the array nums after the possible rotation and an integer target, return the index of target if it is in nums, or -1 if it is not in nums. You must write an algorithm with O(log n) runtime complexity.").examples("Input: nums = [4,5,6,7,0,1,2], target = 0\nOutput: 4").constraints("1 <= nums.length <= 5000").tags("array, binary-search").youtubeLink("https://www.youtube.com/watch?v=U8XENwh8UhW").leetcodeLink("https://leetcode.com/problems/search-in-rotated-sorted-array/").solved(false).build(),
            DSAProblem.builder().title("Trapping Rain Water").difficulty("Hard").topic("Two Pointers").description("Given n non-negative integers representing an elevation map where the width of each bar is 1, compute how much water it can trap after raining.").examples("Input: height = [0,1,0,2,1,0,1,3,2,1,2,1]\nOutput: 6").constraints("n == height.length\n1 <= n <= 2 * 10^4").tags("array, two-pointers, dynamic-programming, stack").youtubeLink("https://www.youtube.com/watch?v=ZI2z5pq0TqA").leetcodeLink("https://leetcode.com/problems/trapping-rain-water/").solved(false).build()
        ));
    }

    private void seedInterviewQuestions() {
        interviewQuestionRepository.saveAll(Arrays.asList(
            InterviewQuestion.builder().category("Java").difficulty("Intermediate").question("What is the difference between equals() and == in Java?").answer("== is an operator that compares the memory addresses (object references) of two objects, whereas the equals() method compares the actual content or state of the objects.").explanation("When comparing primitive types, == compares their values. When comparing objects, == checks if they point to the same memory location. The equals() method is defined in the Object class and can be overridden by custom classes to provide logical equality checks (e.g., comparing two String objects' characters).").build(),
            InterviewQuestion.builder().category("Java").difficulty("Advanced").question("Explain the concept of ConcurrentHashMap and how it differs from HashMap and Hashtable.").answer("ConcurrentHashMap is a thread-safe implementation of Map in Java. It allows concurrent read and write operations without locking the entire map, unlike Hashtable. It differs from HashMap, which is not thread-safe.").explanation("ConcurrentHashMap achieves high concurrency by dividing the map into segments (in Java 7) or using CAS and synchronized blocks on individual buckets (Java 8+). Hashtable locks the entire map for every operation, leading to poor performance in highly concurrent environments.").build(),
            InterviewQuestion.builder().category("Java").difficulty("Intermediate").question("What is the Java Memory Model (JMM)?").answer("The Java Memory Model specifies how threads in Java interact through memory. It dictates how and when changes made by one thread to a shared variable become visible to other threads.").explanation("Key concepts in JMM include visibility and ordering. Keywords like volatile, synchronized, and final play a crucial role in establishing happens-before relationships to ensure data consistency across threads.").build(),
            InterviewQuestion.builder().category("Java").difficulty("Beginner").question("What are the differences between an interface and an abstract class?").answer("An interface can only contain abstract methods (until Java 8 introduced default/static methods) and cannot have state (instance variables). An abstract class can have both abstract and non-abstract methods, and can maintain state. A class can implement multiple interfaces but extend only one abstract class.").explanation("Use abstract classes when sharing code among closely related classes. Use interfaces to define a contract for unrelated classes to implement.").build(),
            InterviewQuestion.builder().category("Java").difficulty("Advanced").question("How does Garbage Collection work in Java?").answer("Garbage collection is the process of automatically reclaiming memory by destroying objects that are no longer reachable by any live thread. Java uses generational garbage collection.").explanation("The heap is divided into Young Generation (Eden, Survivor spaces) and Old Generation. Minor GCs clean the Young Generation, while Major GCs clean the Old Generation. Different collectors like G1GC or ZGC optimize for pause times or throughput.").build(),
            
            InterviewQuestion.builder().category("DBMS").difficulty("Beginner").question("What is Normalization? Explain the First Normal Form (1NF).").answer("Normalization is the process of organizing data in a database to reduce redundancy and improve data integrity. 1NF requires that each column contains atomic (indivisible) values and each record is unique.").explanation("In 1NF, you cannot have a comma-separated list of values in a single column. This ensures querying and indexing are efficient and straightforward.").build(),
            InterviewQuestion.builder().category("DBMS").difficulty("Intermediate").question("Explain ACID properties in a transaction.").answer("ACID stands for Atomicity (all or nothing), Consistency (valid state before and after), Isolation (concurrent transactions don't interfere), and Durability (committed data is saved permanently).").explanation("These properties guarantee that database transactions are processed reliably, which is crucial in systems like banking where partial failures are unacceptable.").build(),
            InterviewQuestion.builder().category("DBMS").difficulty("Advanced").question("What is an index, and how does a B-Tree index work?").answer("An index is a data structure that improves the speed of data retrieval operations. A B-Tree (Balanced Tree) index keeps data sorted and allows searches, sequential access, insertions, and deletions in logarithmic time.").explanation("B-Trees minimize disk I/O operations because each node can have many children, resulting in a shallow tree depth. When a query is executed, the database traverses the tree from root to leaf to find the pointer to the actual data row.").build(),
            InterviewQuestion.builder().category("DBMS").difficulty("Intermediate").question("What is the difference between INNER JOIN and LEFT JOIN?").answer("INNER JOIN returns only the rows where there is a match in both tables. LEFT JOIN returns all rows from the left table, and the matched rows from the right table (or NULL if no match).").explanation("LEFT JOIN is useful when you want to keep all records from a primary table regardless of whether they have related data in a secondary table.").build(),
            InterviewQuestion.builder().category("DBMS").difficulty("Advanced").question("Explain Deadlock in DBMS and how to prevent it.").answer("A deadlock occurs when two or more transactions are waiting for each other to release locks, causing an infinite wait. Prevention techniques include acquiring all needed locks at once or imposing an ordering on lock acquisition.").explanation("Deadlock detection algorithms can also be used, where the DB periodically checks for cycles in the wait-for graph and aborts one of the transactions to break the deadlock.").build(),
            
            InterviewQuestion.builder().category("OS").difficulty("Intermediate").question("What is the difference between a process and a thread?").answer("A process is an independent program in execution with its own memory space. A thread is a lightweight unit of execution within a process that shares the same memory space and resources as other threads in that process.").explanation("Context switching between threads is faster than between processes because there is no need to switch memory contexts.").build(),
            InterviewQuestion.builder().category("OS").difficulty("Advanced").question("Explain virtual memory and paging.").answer("Virtual memory gives the illusion of a large continuous memory to an application, while it is actually fragmented in physical RAM or paged to disk. Paging divides memory into fixed-size blocks called pages (logical) and frames (physical).").explanation("When a process accesses a page not in RAM, a page fault occurs, and the OS brings it from the disk. This allows running programs larger than physical memory.").build(),
            InterviewQuestion.builder().category("OS").difficulty("Beginner").question("What is a deadlock in Operating Systems? What are the 4 necessary conditions?").answer("Deadlock is a state where a set of processes are blocked because each is holding a resource and waiting for another. Conditions: Mutual Exclusion, Hold and Wait, No Preemption, Circular Wait.").explanation("All four conditions must hold simultaneously for a deadlock to occur. Breaking any of them prevents deadlocks.").build(),
            InterviewQuestion.builder().category("OS").difficulty("Intermediate").question("What is a mutex and how is it different from a semaphore?").answer("A mutex is a locking mechanism used to synchronize access to a resource, allowing only one thread at a time. A semaphore is a signaling mechanism that allows a specified number of threads to access a resource.").explanation("A mutex has ownership (only the thread that locked it can unlock it), while a semaphore can be signaled by any thread. A binary semaphore acts similarly to a mutex but lacks ownership.").build(),
            InterviewQuestion.builder().category("OS").difficulty("Advanced").question("Explain the concept of thrashing.").answer("Thrashing occurs when a computer's virtual memory subsystem is in a constant state of paging, spending more time swapping pages in and out of memory than executing actual processes.").explanation("It typically happens when too many processes are running or the memory is over-committed, leading to a severe degradation in performance.").build(),
            
            InterviewQuestion.builder().category("CN").difficulty("Beginner").question("What is the OSI model? Name its 7 layers.").answer("The OSI model is a conceptual framework that standardizes network communication. Layers: Physical, Data Link, Network, Transport, Session, Presentation, Application.").explanation("It helps to understand and troubleshoot networks by dividing the communication process into smaller, manageable layers.").build(),
            InterviewQuestion.builder().category("CN").difficulty("Intermediate").question("What is the difference between TCP and UDP?").answer("TCP is a connection-oriented, reliable protocol with error-checking and flow control. UDP is a connectionless, unreliable protocol that is faster but does not guarantee delivery or order.").explanation("Use TCP for web browsing or file transfers where data integrity is critical. Use UDP for video streaming or gaming where speed is more important than occasional packet loss.").build(),
            InterviewQuestion.builder().category("CN").difficulty("Advanced").question("Explain the TCP 3-way handshake.").answer("The 3-way handshake establishes a TCP connection. 1. Client sends SYN (synchronize). 2. Server replies with SYN-ACK (synchronize-acknowledge). 3. Client sends ACK (acknowledge).").explanation("This ensures both sides are ready to transmit and receive data, and synchronizes their initial sequence numbers.").build(),
            
            InterviewQuestion.builder().category("HR").difficulty("Beginner").question("Tell me about a time you faced a conflict in a team.").answer("I once disagreed with a colleague on the architecture of a new feature. I suggested we list the pros and cons of both approaches. We presented our findings to the team and collectively chose the best solution, which was a hybrid.").explanation("The interviewer is looking for your ability to handle disagreements professionally, without ego, and focusing on the project's success.").build(),
            InterviewQuestion.builder().category("HR").difficulty("Intermediate").question("What is your biggest weakness?").answer("I sometimes focus too much on details, which can slow down my initial progress. To counter this, I now set strict time boxes for tasks and regularly zoom out to ensure I'm aligned with the big picture.").explanation("A good answer shows self-awareness and proactive steps you are taking to improve, rather than giving a humblebrag like 'I work too hard'.").build()
        ));
    }
}
